from __future__ import annotations

import codecs


class IncrementalUTF8Decoder:
    """Turn generated byte-token IDs into valid incremental Unicode text."""

    def __init__(self) -> None:
        self._decoder = codecs.getincrementaldecoder("utf-8")(errors="replace")

    def decode(self, token_id: int | None, *, final: bool) -> str:
        data = b"" if token_id is None else bytes((token_id,))
        return self._decoder.decode(data, final=final)


class ByteTokenizer:
    """A checkpoint-free tokenizer for testing HTTP and streaming mechanics."""

    vocab_size = 256

    def encode(self, text: str) -> list[int]:
        if not isinstance(text, str) or not text:
            raise ValueError("prompt must be a non-empty string")
        return list(text.encode("utf-8"))

    def decode(self, token_ids: list[int]) -> str:
        self._validate(token_ids)
        return bytes(token_ids).decode("utf-8", errors="replace")

    def new_incremental_decoder(self) -> IncrementalUTF8Decoder:
        return IncrementalUTF8Decoder()

    def _validate(self, token_ids: list[int]) -> None:
        if any(
            not isinstance(token_id, int)
            or isinstance(token_id, bool)
            or not 0 <= token_id < self.vocab_size
            for token_id in token_ids
        ):
            raise ValueError("byte token IDs must be integers in [0, 255]")
